### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by piegamesde** [oliverwatkins/swing_library#4]
This project does not have any license specified, defaulting to "All rights reserved". To be able to use this project in other project, it needs a license granting the permission to do so.

**Comment by SeeSharpSoft** [comment]
👍 Any chance for getting information about the license?

**Comment by piegamesde** [comment]
No, but you can use the contributions I made under the MIT license

**Comment by SeeSharpSoft** [comment]
I was mainly interested in using the "Row Number Columns" part - no license (or contribution) provided here, so I won't touch it.

**Comment by oliverwatkins** [comment]
pease touch it. I have been lazy and not added a license. I will get around to it hopefully today

**Comment by piegamesde** [comment]
Closed by #9
